name: Upstream Sync

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync upstream changes
        run: |
          git remote add upstream https://github.com/dreamhunter2333/cloudflare_temp_email.git
          git fetch upstream
          git merge upstream/main --no-edit
          git push origin main
